[tool.poetry]
name = "smallflex-vpp-codes"
version = "0.1.0"
description = ""
authors = ["Tomasini Luca <luca.tomasini@heig-vd.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.10.0"
pyocclient = "^0.6"
tqdm = "^4.66.5"
pyarrow = "^17.0.0"
coloredlogs = "^15.0.1"
dynaconf = "^3.2.6"
duckdb = "^1.1.2"
patito = "^0.8.0"
jinja2 = "^3.1.4"
fastexcel = "^0.12.0"
rpy2 = "3.1"
plotly = "^5.24.1"
ipykernel = "^6.29.5"
pandas = "^2.2.3"
nbformat = "^5.10.4"
streamlit = "^1.39.0"
pyomo = "^6.8.0"
gurobipy = "^11.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
