[project]
name = "smallflex-vpp-codes"
version = "0.1.0"
description = ""
authors = [
    {name = "Tomasini Luca",email = "luca.tomasini@heig-vd.ch"}
]
readme = "README.md"
requires-python = "^3.12"

package-mode = false
dependencies = [
    "utility-functions @ git+ssh://git@github.com/heig-vd-ie/utility-functions.git",
    "pyomo (>=6.9.2,<7.0.0)",
    "plotly (>=6.1.1,<7.0.0)",
    "gurobipy (>=12.0.2,<13.0.0)",
    "patito (>=0.8.3,<0.9.0)",
    "smallflex-data-schema @ git+ssh://git@github.com/heig-vd-ie/smallflex_data_schema.git"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
