[tool.poetry]
name = "smallflex-vpp-codes"
version = "0.1.0"
description = ""
authors = ["Tomasini Luca <luca.tomasini@heig-vd.ch>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.10.0"
pyocclient = "^0.6"
tqdm = "^4.66.5"
pyarrow = "^17.0.0"
coloredlogs = "^15.0.1"
dynaconf = "^3.2.6"
duckdb = "^1.1.2"
patito = "^0.8.0"
jinja2 = "^3.1.4"
fastexcel = "^0.12.0"
rpy2 = "3.1"
plotly = "^5.24.1"
ipykernel = "^6.29.5"
pandas = "^2.2.3"
nbformat = "^5.10.4"
streamlit = "^1.39.0"
pyomo = "^6.8.0"
gurobipy = "^11.0.3"
kaleido = "0.2.1"
sphinx = "^8.1.3"
nbsphinx = "^0.9.5"
myst-parser = "^4.0.0"
sphinx-copybutton = "^0.5.2"
pydata-sphinx-theme = "^0.16.0"
sphinx-rtd-size = "^0.2.0"
sphinx-rtd-theme = "^3.0.2"
ghp-import = "^2.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
